// packages/simplebar-react/index.js
import React from 'react';
import PropTypes from 'prop-types';
import 'simplebar';

export default function SimpleBar({ children, ...options }) {
  return (
    <div data-simplebar {...options}>
      <div className="simplebar-wrapper">
        <div className="simplebar-height-auto-observer-wrapper">
          <div className="simplebar-height-auto-observer"></div>
        </div>
        <div className="simplebar-mask">
          <div className="simplebar-offset">
            <div className="simplebar-content">
              {children}
            </div>
          </div>
        </div>
        <div className="simplebar-placeholder" />
      </div>
      <div className="simplebar-track horizontal">
        <div className="simplebar-scrollbar" />
      </div>
      <div className="simplebar-track vertical">
        <div className="simplebar-scrollbar" />
      </div>
    </div>
  );
}

SimpleBar.propTypes = {
  children: PropTypes.node
};

// packages/simplebar-angular/src/lib/simplebar-angular.component.ts
import {
  Component,
  OnInit,
  Input,
  AfterViewInit,
  ElementRef,
  ViewEncapsulation
} from '@angular/core';

import SimpleBar from 'simplebar/dist/simplebar-core.esm';
import { Options } from 'simplebar';

@Component({
  selector: 'ngx-simplebar',
  host: { 'data-simplebar': 'init' },
  templateUrl: './simplebar-angular.component.html',
  styleUrls: [
    '../../../simplebar/src/simplebar.css',
    './simplebar-angular.component.scss'
  ],
  encapsulation: ViewEncapsulation.None
})
export class SimplebarAngularComponent implements OnInit, AfterViewInit {
  @Input('options') options: Options;

  elRef: ElementRef;
  SimpleBar: any;

  constructor(elRef: ElementRef) {
    this.elRef = elRef;
  }

  ngOnInit() {}

  ngAfterViewInit(): void {
    this.SimpleBar = new SimpleBar(this.elRef.nativeElement, this.options || {});
  }

  ngOnDestroy() {
    this.SimpleBar.unMount();
    this.SimpleBar = null;
  }
}

<div class="simplebar-wrapper">
  <div class="simplebar-height-auto-observer-wrapper">
    <div class="simplebar-height-auto-observer"></div>
  </div>
  <div class="simplebar-mask">
    <div class="simplebar-offset">
      <div class="simplebar-content-wrapper">
        <div class="simplebar-content">
          <ng-content></ng-content>
        </div>
      </div>
    </div>
  </div>
  <div class="simplebar-placeholder"></div>
</div>
<div class="simplebar-track simplebar-horizontal">
  <div class="simplebar-scrollbar"></div>
</div>
<div class="simplebar-track simplebar-vertical">
  <div class="simplebar-scrollbar"></div>
</div>
